[tool.poetry]
name = "lyra_graphtool_test"
version = "0.1.2"
description = "Lyra Graphtool"
authors = ["Studio X, LLC"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.24.3"
matplotlib = "^3.7.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.2"
pytest-cov = "^4.1.0"
python-semantic-release = "^7.34.3"
sphinx-rtd-theme = "^1.2.2"
nbsphinx = "^0.9.2"
pygments = "^2.15.1"
myst-nb = "^0.17.2"
jupyter = "^1.0.0"
nbconvert = "^7.5.0"

[tool.semantic_release]
version_variable = [
    "src/lyra_graphtool_test/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "main"                             # branch to make releases of
changelog_file = "CHANGELOG.md"             # changelog file
build_command = "poetry build"              # build dists
dist_path = "dist/"                         # where to put dists
upload_to_release = true                    # auto-create GitHub release
upload_to_pypi = false                      # don't auto-upload to PyPI
remove_dist = false                         # don't remove dists
patch_without_tag = true                    # patch release by default

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
