[tool.poetry]
name = "sidetrek"
version = "0.0.109"
description = ""
authors = ["Seungchan Lee <seunggs@gmail.com>"]
readme = "README.md"
exclude = ["sidetrek/test/**"]

[tool.poetry.scripts]
sidetrek = "sidetrek.cli:app"

[tool.poetry.dependencies]
python = "^3.8,<3.12"
typer = {extras = ["all"], version = "^0.7.0"}
requests = "^2.28.2"
pylint = "^2.17.0"
torchdata = "^0.6.0"
fsspec = "^2023.4.0"
s3fs = "^2023.4.0"
bentoml = "^1.0.20"
mlflow = "^2.3.2"
flytekit = "^1.6.1"
aiohttp = "^3.8.4"
cloudpickle = "^2.2.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
